version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: yourdatabase
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/app
    environment:
      ENV: "development"
      DB_HOST: "db"
      POSTGRES_DB: "yourdatabase"
      POSTGRES_USER: "youruser"
      POSTGRES_PASSWORD: "yourpassword"
      PYTHONPATH: "/app"
      REDIS_URL: "redis://redis:6379"  # 添加了这一行
    depends_on:
      - db
      - redis

volumes:
  postgres_data: